name: chromacs
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - r-base
  - r-biocmanager
  - fontconfig

  # Bioconductor
  - bioconductor-chipseeker
  - bioconductor-diffbind
  - bioconductor-genomicfeatures
  - bioconductor-genomicranges
  - bioconductor-rtracklayer
  - bioconductor-clusterprofiler
  - bioconductor-txdbmaker
  - bioconductor-biomart
  - bioconductor-noiseq

  # CRAN
  - r-ggplot2
  - r-gridextra
  - r-r.utils
  - r-xml2
  - r-openxlsx
  - r-ggrepel                 

  # Python
  - pandas
  - numpy
  - scipy
  - statsmodels
  - pyyaml
  - openpyxl
  - tk=8.6.13=xft_h2e05e87_1                

  # CLI Tools
  - bowtie2
  - samtools
  - fastqc
  - multiqc
  - trim-galore
  - macs3
  - genrich
  - bedtools
  - deeptools
  - subread
  - aria2
  - meme
  
  - pip
  - pip:
      - matplotlib
      - seaborn
      - fpdf
      - pillow
      - TOBIAS
